"""Сделал поле organization_id обязательным полем

Revision ID: 69f7f00e3567
Revises: ad8f21a6249b
Create Date: 2026-08-12 09:24:00.438014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f7f00e3567'
down_revision: Union[str, Sequence[str], None] = 'ad8f21a6249b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Организация')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Организация')
    # ### end Alembic commands ###
