"""Initial migration

Revision ID: 089144b000d4
Revises: 
Create Date: 2026-08-10 08:33:06.667628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089144b000d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False, comment='Наименование организации анг'),
    sa.Column('name_ru', sa.String(length=100), nullable=False, comment='Наименование организации'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_ru')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True, comment='Организация'),
    sa.Column('detection_date', sa.DateTime(), nullable=False, comment='Дата и время выявления угрозы'),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('attack_type', sa.String(length=100), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('destination_ip', sa.String(length=45), nullable=False),
    sa.Column('detection_tool', sa.String(length=10), nullable=False),
    sa.Column('cve', sa.String(length=50), nullable=True),
    sa.Column('host', sa.String(length=50), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('methods', sa.String(length=200), nullable=False),
    sa.Column('protocols_ports', sa.String(length=200), nullable=False),
    sa.Column('potential_impact', sa.Text(), nullable=False),
    sa.Column('risk_assessment', sa.String(length=12), nullable=False),
    sa.Column('data_or_payload', sa.Text(), nullable=False),
    sa.Column('response_actions', sa.Text(), nullable=False),
    sa.Column('file_content', sa.LargeBinary(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports_delivery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.Uuid(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('external_report_id', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports_delivery')
    op.drop_table('reports')
    op.drop_table('organization')
    # ### end Alembic commands ###
